In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("supershop.csv")

In [3]:
df.head()

Marketing Spend  Administration  Transport     Area     Profit
0        114523.61       136897.80  471784.10    Dhaka  192261.83
1        162597.70       151377.59  443898.53      Ctg  191792.06
2        153441.51       101145.55  407934.54  Rangpur  191050.39
3        144372.41       118671.85  383199.62    Dhaka  182901.99
4        142107.34        91391.77  366168.42  Rangpur  166187.94

In [4]:
df1=df2=df3=df4=df5=df6=df7=df8=df9=df10=df.copy() # for Multiple Value Assignment

In [5]:
df.isnull().sum() # Here Transport COlumn has one Null Value

Marketing Spend    0
Administration     0
Transport          1
Area               0
Profit             0
dtype: int64

Now Needed handle null Value we can use mean,Median or Mode

# Measured of Center Tendency

In [6]:
df.Transport.mean() # for calculate Mean Value of Transport

215331.7324489796

In [7]:
df.Transport.median() # for Calculate Median Value Of Transport

214634.81

In [8]:
df.Transport.mode() # for Calculate Mode Value of Transport

0    0.0
Name: Transport, dtype: float64

In [9]:
df.Transport.unique()

array([471784.1 , 443898.53, 407934.54, 383199.62, 366168.42, 362861.36,
       127716.82, 323876.68, 311613.29, 304981.62, 229160.95, 249744.55,
       249839.44, 252664.93, 256512.92, 261776.23, 264346.06, 282574.31,
       294919.57,       nan, 298664.47, 299737.29, 303319.26, 304768.73,
       140574.81, 137962.62, 134050.07, 353183.81, 118148.2 , 107138.38,
        91131.24,  88218.23,  46085.25, 214634.81, 210797.67, 205517.64,
       201126.82, 197029.42, 185265.1 , 174999.3 , 172795.67, 164470.71,
       148001.11,  35534.17,  28334.72,   1903.93, 297114.46,      0.  ,
        45173.06])

In [10]:
df.Transport=df.Transport.fillna(df.Transport.median())

In [11]:
df.isnull().sum()

Marketing Spend    0
Administration     0
Transport          0
Area               0
Profit             0
dtype: int64

In [12]:
df.shape

(50, 5)

# Encoding

In [13]:
df.Area.unique()

array(['Dhaka', 'Ctg', 'Rangpur'], dtype=object)

In [14]:
df.Area=df.Area.replace(['Dhaka', 'Ctg', 'Rangpur'],[0,1,2])

In [15]:
df.head()

Marketing Spend  Administration  Transport  Area     Profit
0        114523.61       136897.80  471784.10     0  192261.83
1        162597.70       151377.59  443898.53     1  191792.06
2        153441.51       101145.55  407934.54     2  191050.39
3        144372.41       118671.85  383199.62     0  182901.99
4        142107.34        91391.77  366168.42     2  166187.94

In [16]:
from sklearn.preprocessing import LabelEncoder

In [17]:
le=LabelEncoder()

In [18]:
df1.Area=le.fit_transform(df1.Area)

In [19]:
df1.head()

Marketing Spend  Administration  Transport  Area     Profit
0        114523.61       136897.80  471784.10     1  192261.83
1        162597.70       151377.59  443898.53     0  191792.06
2        153441.51       101145.55  407934.54     2  191050.39
3        144372.41       118671.85  383199.62     1  182901.99
4        142107.34        91391.77  366168.42     2  166187.94

# if we have Multiple column for needed Label Encoder

In [20]:
columns=df2.columns

In [21]:
columns

Index(['Marketing Spend', 'Administration', 'Transport', 'Area', 'Profit'], dtype='object')

In [22]:
for col in columns:
    if df2[col].dtype==np.number:
        continue
    df2[col]=le.fit_transform(df[col])

C:\Users\Youtech BD\AppData\Local\Temp\ipykernel_23720\1315794100.py:2: DeprecationWarning: Converting `np.inexact` or `np.floating` to a dtype is deprecated. The current result is `float64` which is not strictly correct.
  if df2[col].dtype==np.number:


In [23]:
df2.head()

Marketing Spend  Administration  Transport  Area     Profit
0        114523.61       136897.80  471784.10     0  192261.83
1        162597.70       151377.59  443898.53     1  191792.06
2        153441.51       101145.55  407934.54     2  191050.39
3        144372.41       118671.85  383199.62     0  182901.99
4        142107.34        91391.77  366168.42     2  166187.94

In [24]:
# if we want remove warning
import warnings as wr
wr.filterwarnings('ignore')

for col in columns:
    if df3[col].dtype==np.number:
        continue
    df3[col]=le.fit_transform(df[col])

In [25]:
df3.head()

Marketing Spend  Administration  Transport  Area     Profit
0        114523.61       136897.80  471784.10     0  192261.83
1        162597.70       151377.59  443898.53     1  191792.06
2        153441.51       101145.55  407934.54     2  191050.39
3        144372.41       118671.85  383199.62     0  182901.99
4        142107.34        91391.77  366168.42     2  166187.94

In [26]:
# Second Way for Handle Error
from pandas.core.dtypes.common import is_numeric_dtype

In [27]:
for col in df4.columns:
    if is_numeric_dtype(df4[col]):
        continue
    df4[col]=le.fit_transform(df4[col])

In [28]:
df4.head()

Marketing Spend  Administration  Transport  Area     Profit
0        114523.61       136897.80  471784.10     0  192261.83
1        162597.70       151377.59  443898.53     1  191792.06
2        153441.51       101145.55  407934.54     2  191050.39
3        144372.41       118671.85  383199.62     0  182901.99
4        142107.34        91391.77  366168.42     2  166187.94

3. One Hot Encoder() 

In [29]:
df8.head()

Marketing Spend  Administration  Transport  Area     Profit
0        114523.61       136897.80  471784.10     0  192261.83
1        162597.70       151377.59  443898.53     1  191792.06
2        153441.51       101145.55  407934.54     2  191050.39
3        144372.41       118671.85  383199.62     0  182901.99
4        142107.34        91391.77  366168.42     2  166187.94

In [30]:
df=pd.read_csv("supershop.csv")

In [31]:
df1=df2=df3=df4=df5=df6=df.copy()

In [32]:
dummy=pd.get_dummies(df.Area)

In [33]:
dummy.head()

Ctg  Dhaka  Rangpur
0    0      1        0
1    1      0        0
2    0      0        1
3    0      1        0
4    0      0        1

In [34]:
df.drop('Area',axis='columns',inplace=True)

In [35]:
df.head()

Marketing Spend  Administration  Transport     Profit
0        114523.61       136897.80  471784.10  192261.83
1        162597.70       151377.59  443898.53  191792.06
2        153441.51       101145.55  407934.54  191050.39
3        144372.41       118671.85  383199.62  182901.99
4        142107.34        91391.77  366168.42  166187.94

# Dummy Trap

In [36]:
dummy1=pd.get_dummies(df1.Area,drop_first=True)
dummy1.head()

Dhaka  Rangpur
0      1        0
1      0        0
2      0        1
3      1        0
4      0        1

In [37]:
df=pd.concat([df,dummy1],axis=1)

In [38]:
df.head()

Marketing Spend  Administration  Transport     Profit  Dhaka  Rangpur
0        114523.61       136897.80  471784.10  192261.83      1        0
1        162597.70       151377.59  443898.53  191792.06      0        0
2        153441.51       101145.55  407934.54  191050.39      0        1
3        144372.41       118671.85  383199.62  182901.99      1        0
4        142107.34        91391.77  366168.42  166187.94      0        1

In [39]:
city =df2.Area.unique()

In [40]:
city

array(['Dhaka', 'Ctg', 'Rangpur'], dtype=object)

In [41]:
from sklearn.preprocessing import OrdinalEncoder

In [42]:
enco=OrdinalEncoder(categories=[city])

In [43]:
enco.fit(df2[['Area']])

OrdinalEncoder(categories=[array(['Dhaka', 'Ctg', 'Rangpur'], dtype=object)])

In [44]:
enco.transform(df2[['Area']])

array([[0.],
       [1.],
       [2.],
       [0.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [1.],
       [2.],
       [1.],
       [2.],
       [0.],
       [1.],
       [0.],
       [2.],
       [0.],
       [1.],
       [0.],
       [2.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [2.],
       [0.],
       [2.],
       [0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [1.],
       [1.],
       [2.],
       [1.],
       [0.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [1.]])

In [45]:
encoded_values=enco.fit_transform(df2[['Area']])

In [46]:
encoded_values

array([[0.],
       [1.],
       [2.],
       [0.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [1.],
       [2.],
       [1.],
       [2.],
       [0.],
       [1.],
       [0.],
       [2.],
       [0.],
       [1.],
       [0.],
       [2.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [2.],
       [0.],
       [2.],
       [0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [1.],
       [1.],
       [2.],
       [1.],
       [0.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [1.]])